name: check, build, deploy hpc-carpentry.org

on:
  push:
    branches: main
  pull_request:
    branches:
      - main

jobs:
  build-website:
    if: github.repository_owner == 'hpc-carpentry'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@master

      - name: Set up Ruby
        uses: actions/setup-ruby@main
        with:
          ruby-version: '2.7.x'

      - name: Install yaml-lint
        run: |
          gem install yaml-lint

      - name: Lint _config.yml with yaml-lint
        run: |
          yaml-lint  _config.yml

      - name: Lint pages and blog posts
        run: |
          yaml-lint -q -n $(find _posts -regex ".*.md\|.*html") &&\
          yaml-lint -q -n $(find pages -regex ".*.md\|.*html")

      - name: Get GeoJSON for instructor map
        run: |
          curl --remote-name-all https://feeds.carpentries.org/all_instructors_by_airport.geojson &&\
          cp all_instructors_by_airport.geojson files/.

      - name: Create repository data files
        uses: eessi/github-action-eessi@v1
        shell: bash
        env:
          GITHUB_PAT: ${{ secrets.JEKYLL_PAT }}
        run: |
          module load R
          make data

#      - name: Create PDF file of some pages
#        uses: docker://pandoc/latex:latest
#        with:
#          args: >
#            --output files/pdf/online-workshop-recommendations.pdf
#            --pdf-engine=xelatex
#            -V geometry:margin=1in
#            pages/online-workshop-recommendations.md

      - name: Build and deploy gh-pages branch
        uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: 'gh-pages'
